export const pages = [
  "/alert-bookmarked-login.html",
  "/alert-retry-sign-on-process.html",
  "/cms-faq-eventually.html",
  "/cms-privacy-security-legal.html",
  "/error-back-button-error.html",
  "/error-clock-skew-wrong-acs-url-sp-not-registered.html",
  "/error-environment-fail.html",
  "/error-generic-failsafe.html",
  "/error-http-403-404.html",
  "/error-http-500s.html",
  "/error-new.html",
  "/index.html",
  "/login-attempts-slowed-timer-over.html",
  "/login-attempts-slowed-timer-running.html",
  "/logon-form-after-failed-login.html",
  "/logon-form-timed-out.html",
  "/logon-form-w-breaking-news-message.html",
  "/logon-form-w-custom-sp-news.html",
  "/logon-form-w-medcenter-login.html",
  "/logout-page.html",
  "/mfa-introduction.html",
  "/redirecting-to-initial-login.html",
  "/success-goto-idp-sp.html"
] as const
